# Generated by Django 3.2.16 on 2022-11-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefname', models.CharField(max_length=4, verbose_name='都道府県名')),
            ],
            options={
                'verbose_name_plural': 'Prefecture',
            },
        ),
    ]
