# Generated by Django 3.2.16 on 2022-11-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_name', models.CharField(max_length=100, verbose_name='サブスクリプション名')),
                ('subscription_detail', models.TextField(verbose_name='サブスクリプション内容')),
                ('subscription_rate', models.IntegerField(verbose_name='サブスクリプション料金')),
                ('subscription_period', models.IntegerField(verbose_name='サブスクリプション期間')),
            ],
            options={
                'verbose_name_plural': 'subscription',
            },
        ),
    ]
