# Generated by Django 3.2.16 on 2022-11-29 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_pswd', models.CharField(max_length=20, verbose_name='パスワード')),
                ('hospital_mail', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('hospital_name', models.CharField(max_length=30, verbose_name='病院名')),
                ('hospital_address2', models.CharField(max_length=100, verbose_name='住所2')),
                ('hospital_tel', models.CharField(max_length=11, verbose_name='固定電話番号')),
                ('hospital_doctor', models.CharField(max_length=20, verbose_name='院長名')),
                ('hospital_access', models.TextField(verbose_name='アクセス')),
                ('hospital_info', models.TextField(blank=True, null=True, verbose_name='お知らせ')),
                ('bank_name', models.CharField(max_length=4, verbose_name='銀行コード')),
                ('bank_brunchnum', models.CharField(max_length=4, verbose_name='支店コード')),
                ('bank_type', models.CharField(max_length=2, verbose_name='口座種類')),
                ('bank_num', models.CharField(max_length=8, verbose_name='口座番号')),
                ('bank_hospital_name', models.CharField(max_length=30, verbose_name='口座名義')),
                ('start', models.DateField(blank=True, null=True, verbose_name='契約開始日')),
                ('end', models.DateField(blank=True, null=True, verbose_name='契約終了日')),
                ('hospital_created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('hospital_updated', models.DateTimeField(auto_now_add=True, verbose_name='更新日時')),
                ('FK_subscriptionID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.subscription', verbose_name='サブスクリプションID')),
                ('hospital_address1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.prefecture', verbose_name='住所1')),
            ],
            options={
                'verbose_name_plural': 'Hospital',
            },
        ),
    ]
