# Generated by Django 3.2.16 on 2022-11-29 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.hospital', verbose_name='病院ID')),
                ('typeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.type', verbose_name='種類ID')),
            ],
            options={
                'verbose_name_plural': 'Ok',
            },
        ),
    ]
